spring:
  application:
    name: banddy

  config:
    import: optional:file:./.env[.properties]

  datasource:
    url: jdbc:mysql://localhost:3306/banddy
    username: root
    password: fire4284
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: never
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        show_sql: true
        format_sql: true
        use_sql_comments: true
        hbm2ddl:
          auto: update
        default_batch_fetch_size: 1000